In [150]:
import numpy as np
import pandas as pd

In [151]:
data = {
    "Name":['Ali','Hassan','Usman','Zubair'],
    "Age":[18,21,19,20],
    "City":['Lahore','Islamabad','Karachi','Faisalabad']
}

In [152]:
df = pd.DataFrame(data)

In [153]:
print(df)

     Name  Age        City
0     Ali   18      Lahore
1  Hassan   21   Islamabad
2   Usman   19     Karachi
3  Zubair   20  Faisalabad

In [154]:
df.to_csv("sample12.csv",index = False)

In [155]:
# now lets import data from csv
df = pd.read_csv("Messy_Employment_India_Dataset.csv")

In [156]:
print(df)

          Status Age Group    Education    Industry   Location   AI Risk  \
0       EMPLOYED     25_34  high school  Technology      Urban       NaN
1       EMPLOYED     18-24      Diploma     Fintech      rural  moderate
2       EMPLOYED     25_34  High School      Retail      Delhi       Low
3     UNEMPLOYED     18-24      Masters      Retail      Urban       Low
4            NaN     45-54      Diploma     Fintech  Hyderabad       low
...          ...       ...          ...         ...        ...       ...
1995    employed     25-34         Ph.D     Finance  Hyderabad       Low
1996    EMPLOYED     25-34          PhD       Tech         NaN       NaN
1997         NaN   35 - 44      Masters   Education        NaN       low
1998    EMPLOYED     25_34  high school      Retail     Mumbai      HIGH
1999  UNEMPLOYED     25_34  High School         NaN        NaN  moderate

      Years of Experience  Monthly Salary (INR) Date Recorded
0                     NaN               40700.0      1/1/2023
1                     NaN               17500.0      1/2/2023
2                    16.0               77600.0      1/3/2023
3                    30.0              100200.0      1/4/2023
4                     9.0               19500.0      1/5/2023
...                   ...                   ...           ...
1995                  NaN              113000.0     6/18/2028
1996                 22.0              102200.0     6/19/2028
1997                  NaN               31600.0     6/20/2028
1998                 22.0               92500.0     6/21/2028
1999                  NaN               43300.0     6/22/2028

[2000 rows x 9 columns]

In [157]:
df = df.rename(columns = {"Years of Experience":"Years Exp"})

In [158]:
df.head()

,Status,Age Group,Education,Industry,Location,AI Risk,Years Exp,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,NaN,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023

In [159]:
# now there are three issues
# 1. rows,colums?
# 2. what type of?
# 3. missing data?
# so for this we use info() method , it tells no of rows,columns, column names, data type, non null counts, memory usage of dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Status                1732 non-null   object
 1   Age Group             1768 non-null   object
 2   Education             1804 non-null   object
 3   Industry              1799 non-null   object
 4   Location              1787 non-null   object
 5   AI Risk               1716 non-null   object
 6   Years Exp             980 non-null    float64
 7   Monthly Salary (INR)  1613 non-null   float64
 8   Date Recorded         2000 non-null   object
dtypes: float64(2), object(7)
memory usage: 140.8+ KB

In [160]:
df.describe()

        Years Exp  Monthly Salary (INR)
count  980.000000           1613.000000
mean    15.244898          76886.360818
std      9.103941          41628.008054
min      0.000000           5100.000000
25%      7.000000          40700.000000
50%     16.000000          77200.000000
75%     23.000000         112400.000000
max     30.000000         149900.000000

In [161]:
df.shape # use to quickly know the size of dataset

(2000, 9)

In [162]:
df.columns

Index(['Status', 'Age Group', 'Education', 'Industry', 'Location', 'AI Risk',
       'Years Exp', 'Monthly Salary (INR)', 'Date Recorded'],
      dtype='object')

In [163]:
# how to select specific column
# filter rows
# combine multiple conditions

# selecting single and multiple columns
df["Years Exp"]

0        NaN
1        NaN
2       16.0
3       30.0
4        9.0
        ...
1995     NaN
1996    22.0
1997     NaN
1998    22.0
1999     NaN
Name: Years Exp, Length: 2000, dtype: float64

In [164]:
df[["Years Exp","Age Group"]]

      Years Exp Age Group
0           NaN     25_34
1           NaN     18-24
2          16.0     25_34
3          30.0     18-24
4           9.0     45-54
...         ...       ...
1995        NaN     25-34
1996       22.0     25-34
1997        NaN   35 - 44
1998       22.0     25_34
1999        NaN     25_34

[2000 rows x 2 columns]

In [165]:
# row filtering based on the single condition
filtered_row = df[df["Monthly Salary (INR)"] > 149000]
filtered_row

,Status,Age Group,Education,Industry,Location,AI Risk,Years Exp,Monthly Salary (INR),Date Recorded
704,unemployed,45-54,High School,Tech,rural,low,23.0,149200.0,12/5/2024
1121,UNEMPLOYED,35 - 44,Diploma,Finance,rural,HIGH,NaN,149900.0,1/26/2026
1187,NaN,25_34,Ph.D,Retail,urban,Low,23.0,149100.0,4/2/2026
1211,EMPLOYED,35 - 44,Ph.D,Technology,suburban,moderate,30.0,149800.0,4/26/2026
1546,UNEMPLOYED,18 to 24,High School,Tech,Mumbai,low,NaN,149100.0,3/27/2027
1565,NaN,35 - 44,Bachelor's,Retail,rural,NaN,NaN,149300.0,4/15/2027
1595,employed,18-24,Diploma,Finance,Delhi,low,NaN,149300.0,5/15/2027
1696,NaN,25-34,Bachelors,Health,urban,HIGH,28.0,149300.0,8/24/2027
1898,UNEMPLOYED,NaN,Bachelors,Retail,urban,moderate,1.0,149600.0,3/13/2028

In [166]:
# row filtering based on the multiple condition
filtered_row_m = df[(df["Monthly Salary (INR)"] > 130000) & (df["Monthly Salary (INR)"] < 132000)]
filtered_row_m

,Status,Age Group,Education,Industry,Location,AI Risk,Years Exp,Monthly Salary (INR),Date Recorded
73,unemployed,45-54,Diploma,Fintech,rural,HIGH,20.0,130700.0,3/15/2023
113,Employed,25-34,NaN,NaN,urban,Medium,1.0,130200.0,4/24/2023
166,unemployed,18-24,Bachelors,Health,Hyderabad,HIGH,NaN,131300.0,6/16/2023
403,employed,NaN,Master,Healthcare,Delhi,moderate,NaN,131000.0,2/8/2024
448,NaN,45-54,high school,Healthcare,Mumbai,NaN,4.0,131700.0,3/24/2024
452,EMPLOYED,NaN,High School,Tech,Bangalore,NaN,19.0,130300.0,3/28/2024
526,UNEMPLOYED,35 - 44,Ph.D,Technology,Hyderabad,low,NaN,130500.0,6/10/2024
671,employed,25_34,NaN,Tech,Bangalore,HIGH,NaN,130800.0,11/2/2024
768,Employed,NaN,NaN,NaN,Delhi,Low,1.0,131600.0,2/7/2025
1086,UNEMPLOYED,NaN,Ph.D,Retail,NaN,moderate,NaN,130700.0,12/22/2025
1118,employed,18-24,Ph.D,Health,Hyderabad,Low,NaN,130100.0,1/23/2026
1304,employed,45-54,Master,NaN,Delhi,High,9.0,131600.0,7/28/2026
1369,Employed,25-34,Ph.D,Retail,Mumbai,Low,NaN,131100.0,10/1/2026
1545,unemployed,35 - 44,high school,Healthcare,Urban,low,NaN,131800.0,3/26/2027
1951,employed,25_34,NaN,Finance,Mumbai,High,NaN,131900.0,5/5/2028
1967,EMPLOYED,18-24,Bachelor's,Finance,NaN,High,24.0,130100.0,5/21/2028

In [167]:
# now adding a new column
df["Bonus"] = df["Monthly Salary (INR)"] * 0.1
df

,Status,Age Group,Education,Industry,Location,AI Risk,Years Exp,Monthly Salary (INR),Date Recorded,Bonus
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,NaN,40700.0,1/1/2023,4070.0
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,1/2/2023,1750.0
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023,7760.0
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023,10020.0
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023,1950.0
...,...,...,...,...,...,...,...,...,...,...
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,NaN,113000.0,6/18/2028,11300.0
1996,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.0,102200.0,6/19/2028,10220.0
1997,NaN,35 - 44,Masters,Education,NaN,low,NaN,31600.0,6/20/2028,3160.0
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.0,92500.0,6/21/2028,9250.0
1999,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,NaN,43300.0,6/22/2028,4330.0

In [168]:
# adding column at specific index so for this we will be using insert
#df.insert(loc,name of new column, values)
df.insert(0 , "Emp_ID", np.random.randint(1,2000 , size = len(df)))
df

,Emp_ID,Status,Age Group,Education,Industry,Location,AI Risk,Years Exp,Monthly Salary (INR),Date Recorded,Bonus
0,1601,EMPLOYED,25_34,high school,Technology,Urban,NaN,NaN,40700.0,1/1/2023,4070.0
1,1758,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,1/2/2023,1750.0
2,1516,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023,7760.0
3,133,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023,10020.0
4,660,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023,1950.0
...,...,...,...,...,...,...,...,...,...,...,...
1995,726,employed,25-34,Ph.D,Finance,Hyderabad,Low,NaN,113000.0,6/18/2028,11300.0
1996,272,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.0,102200.0,6/19/2028,10220.0
1997,1624,NaN,35 - 44,Masters,Education,NaN,low,NaN,31600.0,6/20/2028,3160.0
1998,965,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.0,92500.0,6/21/2028,9250.0
1999,1887,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,NaN,43300.0,6/22/2028,4330.0

In [169]:
del df["Emp_ID"]
df

,Status,Age Group,Education,Industry,Location,AI Risk,Years Exp,Monthly Salary (INR),Date Recorded,Bonus
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,NaN,40700.0,1/1/2023,4070.0
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,1/2/2023,1750.0
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023,7760.0
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023,10020.0
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023,1950.0
...,...,...,...,...,...,...,...,...,...,...
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,NaN,113000.0,6/18/2028,11300.0
1996,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.0,102200.0,6/19/2028,10220.0
1997,NaN,35 - 44,Masters,Education,NaN,low,NaN,31600.0,6/20/2028,3160.0
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.0,92500.0,6/21/2028,9250.0
1999,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,NaN,43300.0,6/22/2028,4330.0

In [170]:
# updating a specific value using loc
df.loc[0, "Years Exp"] = 10.0
df

,Status,Age Group,Education,Industry,Location,AI Risk,Years Exp,Monthly Salary (INR),Date Recorded,Bonus
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,10.0,40700.0,1/1/2023,4070.0
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,1/2/2023,1750.0
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023,7760.0
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023,10020.0
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023,1950.0
...,...,...,...,...,...,...,...,...,...,...
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,NaN,113000.0,6/18/2028,11300.0
1996,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.0,102200.0,6/19/2028,10220.0
1997,NaN,35 - 44,Masters,Education,NaN,low,NaN,31600.0,6/20/2028,3160.0
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.0,92500.0,6/21/2028,9250.0
1999,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,NaN,43300.0,6/22/2028,4330.0

In [171]:
df.drop(columns = ["Bonus"], inplace = True)
df

,Status,Age Group,Education,Industry,Location,AI Risk,Years Exp,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,high school,Technology,Urban,NaN,10.0,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023
...,...,...,...,...,...,...,...,...,...
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,NaN,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.0,102200.0,6/19/2028
1997,NaN,35 - 44,Masters,Education,NaN,low,NaN,31600.0,6/20/2028
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.0,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,NaN,43300.0,6/22/2028

In [172]:
# handling missing values 
df.loc[0,"Education"] = None
df

,Status,Age Group,Education,Industry,Location,AI Risk,Years Exp,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,None,Technology,Urban,NaN,10.0,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,NaN,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.0,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.0,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.0,19500.0,1/5/2023
...,...,...,...,...,...,...,...,...,...
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,NaN,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.0,102200.0,6/19/2028
1997,NaN,35 - 44,Masters,Education,NaN,low,NaN,31600.0,6/20/2028
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.0,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,NaN,43300.0,6/22/2028

In [173]:
df.isnull().sum()

Status                   268
Age Group                232
Education                197
Industry                 201
Location                 213
AI Risk                  284
Years Exp               1019
Monthly Salary (INR)     387
Date Recorded              0
dtype: int64

In [174]:
# as my data has too many Null values i will not use this i will try to fill all the values
# df.dropna(axis = 0, inplace = True) 
# df

In [175]:
# fillna

df["Years Exp"] = df["Years Exp"].fillna(df["Years Exp"].mean())
df

,Status,Age Group,Education,Industry,Location,AI Risk,Years Exp,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,None,Technology,Urban,NaN,10.000000,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,15.239551,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.000000,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.000000,100200.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.000000,19500.0,1/5/2023
...,...,...,...,...,...,...,...,...,...
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,15.239551,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.000000,102200.0,6/19/2028
1997,NaN,35 - 44,Masters,Education,NaN,low,15.239551,31600.0,6/20/2028
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.000000,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,15.239551,43300.0,6/22/2028

In [176]:
df.isnull().sum()

Status                  268
Age Group               232
Education               197
Industry                201
Location                213
AI Risk                 284
Years Exp                 0
Monthly Salary (INR)    387
Date Recorded             0
dtype: int64

In [177]:
df.loc[df["Status"] == "UNEMPLOYED","Monthly Salary (INR)"] = 0
df

,Status,Age Group,Education,Industry,Location,AI Risk,Years Exp,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,None,Technology,Urban,NaN,10.000000,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,15.239551,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.000000,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.000000,0.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.000000,19500.0,1/5/2023
...,...,...,...,...,...,...,...,...,...
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,15.239551,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.000000,102200.0,6/19/2028
1997,NaN,35 - 44,Masters,Education,NaN,low,15.239551,31600.0,6/20/2028
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.000000,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,15.239551,0.0,6/22/2028

In [178]:
df.isnull().sum()

Status                  268
Age Group               232
Education               197
Industry                201
Location                213
AI Risk                 284
Years Exp                 0
Monthly Salary (INR)    332
Date Recorded             0
dtype: int64

In [179]:
df = df.drop(df[(df["Status"].isna()) & (df["Location"].isna())].index)
df

,Status,Age Group,Education,Industry,Location,AI Risk,Years Exp,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,None,Technology,Urban,NaN,10.000000,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,15.239551,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.000000,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.000000,0.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.000000,19500.0,1/5/2023
...,...,...,...,...,...,...,...,...,...
1994,Unemployed,55+,Bachelors,Education,urban,Low,15.239551,9000.0,6/17/2028
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,15.239551,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.000000,102200.0,6/19/2028
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.000000,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,15.239551,0.0,6/22/2028

In [180]:
df.isnull().sum()

Status                  236
Age Group               227
Education               196
Industry                198
Location                181
AI Risk                 282
Years Exp                 0
Monthly Salary (INR)    328
Date Recorded             0
dtype: int64

In [181]:
# handling missing values using interpolation(linear,)    used when time series data is given
df["Monthly Salary (INR)"] = df["Monthly Salary (INR)"].interpolate(method = "linear")
df

,Status,Age Group,Education,Industry,Location,AI Risk,Years Exp,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,None,Technology,Urban,NaN,10.000000,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,15.239551,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.000000,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.000000,0.0,1/4/2023
4,NaN,45-54,Diploma,Fintech,Hyderabad,low,9.000000,19500.0,1/5/2023
...,...,...,...,...,...,...,...,...,...
1994,Unemployed,55+,Bachelors,Education,urban,Low,15.239551,9000.0,6/17/2028
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,15.239551,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.000000,102200.0,6/19/2028
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.000000,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,15.239551,0.0,6/22/2028

In [182]:
df.isnull().sum()

Status                  236
Age Group               227
Education               196
Industry                198
Location                181
AI Risk                 282
Years Exp                 0
Monthly Salary (INR)      0
Date Recorded             0
dtype: int64

In [183]:
df.tail(100)

,Status,Age Group,Education,Industry,Location,AI Risk,Years Exp,Monthly Salary (INR),Date Recorded
1896,NaN,25-34,High School,NaN,urban,NaN,15.239551,42400.0,3/11/2028
1898,UNEMPLOYED,NaN,Bachelors,Retail,urban,moderate,1.000000,0.0,3/13/2028
1899,Unemployed,35 - 44,Masters,Retail,urban,NaN,22.000000,49600.0,3/14/2028
1900,Unemployed,55+,Master,Retail,Bangalore,low,15.239551,24800.0,3/15/2028
1901,UNEMPLOYED,25_34,Bachelors,Fintech,Delhi,Medium,7.000000,0.0,3/16/2028
...,...,...,...,...,...,...,...,...,...
1994,Unemployed,55+,Bachelors,Education,urban,Low,15.239551,9000.0,6/17/2028
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,15.239551,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.000000,102200.0,6/19/2028
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.000000,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,15.239551,0.0,6/22/2028

In [184]:
df["Age Group"] = df["Age Group"].fillna(df["Age Group"].mode()[0])

In [185]:
df.isnull().sum()

Status                  236
Age Group                 0
Education               196
Industry                198
Location                181
AI Risk                 282
Years Exp                 0
Monthly Salary (INR)      0
Date Recorded             0
dtype: int64

In [186]:
df.tail(100)

,Status,Age Group,Education,Industry,Location,AI Risk,Years Exp,Monthly Salary (INR),Date Recorded
1896,NaN,25-34,High School,NaN,urban,NaN,15.239551,42400.0,3/11/2028
1898,UNEMPLOYED,45-54,Bachelors,Retail,urban,moderate,1.000000,0.0,3/13/2028
1899,Unemployed,35 - 44,Masters,Retail,urban,NaN,22.000000,49600.0,3/14/2028
1900,Unemployed,55+,Master,Retail,Bangalore,low,15.239551,24800.0,3/15/2028
1901,UNEMPLOYED,25_34,Bachelors,Fintech,Delhi,Medium,7.000000,0.0,3/16/2028
...,...,...,...,...,...,...,...,...,...
1994,Unemployed,55+,Bachelors,Education,urban,Low,15.239551,9000.0,6/17/2028
1995,employed,25-34,Ph.D,Finance,Hyderabad,Low,15.239551,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.000000,102200.0,6/19/2028
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.000000,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,15.239551,0.0,6/22/2028

In [187]:
df.loc[df["Monthly Salary (INR)"].notna(), "Status"] = "EMPLOYED"
df.loc[df["Monthly Salary (INR)"] == 0.0, "Status"] = "UNEMPLOYED"

In [188]:
df

,Status,Age Group,Education,Industry,Location,AI Risk,Years Exp,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,None,Technology,Urban,NaN,10.000000,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,15.239551,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.000000,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Masters,Retail,Urban,Low,30.000000,0.0,1/4/2023
4,EMPLOYED,45-54,Diploma,Fintech,Hyderabad,low,9.000000,19500.0,1/5/2023
...,...,...,...,...,...,...,...,...,...
1994,EMPLOYED,55+,Bachelors,Education,urban,Low,15.239551,9000.0,6/17/2028
1995,EMPLOYED,25-34,Ph.D,Finance,Hyderabad,Low,15.239551,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.000000,102200.0,6/19/2028
1998,EMPLOYED,25_34,high school,Retail,Mumbai,HIGH,22.000000,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,15.239551,0.0,6/22/2028

In [189]:
df.isnull().sum()

Status                    0
Age Group                 0
Education               196
Industry                198
Location                181
AI Risk                 282
Years Exp                 0
Monthly Salary (INR)      0
Date Recorded             0
dtype: int64

In [190]:
df["Education"].value_counts(dropna=False)

Education
Bachelors      219
Masters        214
High School    201
PhD            200
Bachelor's     199
Diploma        198
Ph.D           197
NaN            195
Master         176
high school    168
None             1
Name: count, dtype: int64

In [191]:
df["Education"] = df["Education"].replace({
    "Bachelors": "Bachelor",
    "Bachelor's": "Bachelor",
    "Masters": "Master",
    "Master": "Master",
    "PhD": "PhD",
    "Ph.D": "PhD",
    "High School": "High School",
    "high school": "High School",
    "None": None
})

In [192]:
df["Education"].value_counts(dropna = False)

Education
Bachelor       418
PhD            397
Master         390
High School    369
Diploma        198
NaN            195
None             1
Name: count, dtype: int64

In [193]:
df["Education"] = df["Education"].replace("NaN", np.nan)

In [194]:
df["Education"].value_counts(dropna = False)

Education
Bachelor       418
PhD            397
Master         390
High School    369
Diploma        198
NaN            195
None             1
Name: count, dtype: int64

In [195]:
df["Education"] = df["Education"].fillna(df["Education"].mode()[0])
df

,Status,Age Group,Education,Industry,Location,AI Risk,Years Exp,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,Bachelor,Technology,Urban,NaN,10.000000,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,15.239551,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.000000,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Master,Retail,Urban,Low,30.000000,0.0,1/4/2023
4,EMPLOYED,45-54,Diploma,Fintech,Hyderabad,low,9.000000,19500.0,1/5/2023
...,...,...,...,...,...,...,...,...,...
1994,EMPLOYED,55+,Bachelor,Education,urban,Low,15.239551,9000.0,6/17/2028
1995,EMPLOYED,25-34,PhD,Finance,Hyderabad,Low,15.239551,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,NaN,NaN,22.000000,102200.0,6/19/2028
1998,EMPLOYED,25_34,High School,Retail,Mumbai,HIGH,22.000000,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,NaN,NaN,moderate,15.239551,0.0,6/22/2028

In [196]:
df.isnull().sum()

Status                    0
Age Group                 0
Education                 0
Industry                198
Location                181
AI Risk                 282
Years Exp                 0
Monthly Salary (INR)      0
Date Recorded             0
dtype: int64

In [197]:
df["Industry"].value_counts(dropna = False)

Industry
Retail        423
Health        208
Healthcare    205
NaN           198
Finance       192
 Fintech      191
Technology    184
Tech          184
Education     183
Name: count, dtype: int64

In [198]:
df["Industry"] = df["Industry"].replace(" Fintech", "Fintech")

In [199]:
df["Industry"].value_counts(dropna = False)

Industry
Retail        423
Health        208
Healthcare    205
NaN           198
Finance       192
Fintech       191
Technology    184
Tech          184
Education     183
Name: count, dtype: int64

In [200]:
df["Industry"] = df["Industry"].fillna(df["Industry"].mode()[0])
df["Location"] = df["Location"].fillna(df["Location"].mode()[0])
df["AI Risk"] = df["AI Risk"].fillna(df["AI Risk"].mode()[0])
df

,Status,Age Group,Education,Industry,Location,AI Risk,Years Exp,Monthly Salary (INR),Date Recorded
0,EMPLOYED,25_34,Bachelor,Technology,Urban,HIGH,10.000000,40700.0,1/1/2023
1,EMPLOYED,18-24,Diploma,Fintech,rural,moderate,15.239551,17500.0,1/2/2023
2,EMPLOYED,25_34,High School,Retail,Delhi,Low,16.000000,77600.0,1/3/2023
3,UNEMPLOYED,18-24,Master,Retail,Urban,Low,30.000000,0.0,1/4/2023
4,EMPLOYED,45-54,Diploma,Fintech,Hyderabad,low,9.000000,19500.0,1/5/2023
...,...,...,...,...,...,...,...,...,...
1994,EMPLOYED,55+,Bachelor,Education,urban,Low,15.239551,9000.0,6/17/2028
1995,EMPLOYED,25-34,PhD,Finance,Hyderabad,Low,15.239551,113000.0,6/18/2028
1996,EMPLOYED,25-34,PhD,Tech,Bangalore,HIGH,22.000000,102200.0,6/19/2028
1998,EMPLOYED,25_34,High School,Retail,Mumbai,HIGH,22.000000,92500.0,6/21/2028
1999,UNEMPLOYED,25_34,High School,Retail,Bangalore,moderate,15.239551,0.0,6/22/2028

In [206]:
df["AI Risk"] = df["AI Risk"].replace({
    "low" : "Low",
    "moderate" : "Moderate",
    "Medium" : "Moderate",
    "HIGH": "High"
})
df["AI Risk"].value_counts(dropna = False)

AI Risk
High        864
Moderate    558
Low         546
Name: count, dtype: int64

In [214]:
df["Age Group"] = df["Age Group"].replace({
    "18 to 24":"18-24",       
    "25_34":"25-34",
    "35 - 44":"35-44" 
})
df["Age Group"].value_counts(dropna = False)

Age Group
18-24    507
25-34    492
45-54    488
35-44    243
55+      238
Name: count, dtype: int64

In [215]:
df.isnull().sum()

Status                  0
Age Group               0
Education               0
Industry                0
Location                0
AI Risk                 0
Years Exp               0
Monthly Salary (INR)    0
Date Recorded           0
dtype: int64

In [216]:
df

,Status,Age Group,Education,Industry,Location,AI Risk,Years Exp,Monthly Salary (INR),Date Recorded
1003,UNEMPLOYED,18-24,Master,Retail,Urban,High,7.000000,0.0,9/30/2025
1414,UNEMPLOYED,18-24,High School,Fintech,urban,Low,15.239551,0.0,11/15/2026
1423,UNEMPLOYED,18-24,High School,Fintech,Mumbai,Low,15.239551,0.0,11/24/2026
1607,UNEMPLOYED,45-54,Master,Healthcare,Bangalore,Moderate,2.000000,0.0,5/27/2027
1624,UNEMPLOYED,25-34,Bachelor,Health,Urban,High,15.239551,0.0,6/13/2027
...,...,...,...,...,...,...,...,...,...
704,EMPLOYED,45-54,High School,Tech,rural,Low,23.000000,149200.0,12/5/2024
1595,EMPLOYED,18-24,Diploma,Finance,Delhi,Low,15.239551,149300.0,5/15/2027
1696,EMPLOYED,25-34,Bachelor,Health,urban,High,28.000000,149300.0,8/24/2027
1565,EMPLOYED,35-44,Bachelor,Retail,rural,High,15.239551,149300.0,4/15/2027
1211,EMPLOYED,35-44,PhD,Technology,suburban,Moderate,30.000000,149800.0,4/26/2026

In [217]:
# sorting
df.sort_values(by = "Monthly Salary (INR)", ascending = True , inplace = True)
df

,Status,Age Group,Education,Industry,Location,AI Risk,Years Exp,Monthly Salary (INR),Date Recorded
1003,UNEMPLOYED,18-24,Master,Retail,Urban,High,7.000000,0.0,9/30/2025
883,UNEMPLOYED,25-34,PhD,Technology,rural,Low,4.000000,0.0,6/2/2025
962,UNEMPLOYED,18-24,Master,Fintech,Bangalore,High,15.239551,0.0,8/20/2025
952,UNEMPLOYED,18-24,High School,Fintech,suburban,High,6.000000,0.0,8/10/2025
950,UNEMPLOYED,55+,PhD,Tech,urban,High,15.239551,0.0,8/8/2025
...,...,...,...,...,...,...,...,...,...
704,EMPLOYED,45-54,High School,Tech,rural,Low,23.000000,149200.0,12/5/2024
1696,EMPLOYED,25-34,Bachelor,Health,urban,High,28.000000,149300.0,8/24/2027
1565,EMPLOYED,35-44,Bachelor,Retail,rural,High,15.239551,149300.0,4/15/2027
1595,EMPLOYED,18-24,Diploma,Finance,Delhi,Low,15.239551,149300.0,5/15/2027
1211,EMPLOYED,35-44,PhD,Technology,suburban,Moderate,30.000000,149800.0,4/26/2026

In [218]:
# aggregation like min max mean median etc etc

avg_salary = df["Monthly Salary (INR)"].mean()
print(avg_salary)

62486.17886178861

In [220]:
# group by and then implementing aggregation methods
grouped = df.groupby(["Age Group"])["Monthly Salary (INR)"].mean()   # finds out avg Salary on specific Age Groups
grouped

Age Group
18-24    60129.296515
25-34    66271.087398
35-44    61142.969822
45-54    63220.314208
55+      59548.809524
Name: Monthly Salary (INR), dtype: float64